version: '2'

services:
  app:
    build:
      context: ./server
    ports:
      - '5555:5555'
    volumes:
      - ./server:/usr/src/app
      # prevents host/container contamination
      - /usr/src/app/node_modules
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    command: npm run dev
  # redis:
  #     image: redis:latest
  #     ports:
  #     - '6379:6379'
